---
title: "About Us"
---

**Mumbai-Online Psychometrics Center (M-OPC)1** is a part of the research project “**Online Psychometrics: Data Science and Public Policy**”. Dr. Vivek Belhekar, Associate Professor at the Department of Applied Psychology, University of Mumbai, is the PI of the project.

The M-OPC has a mandate to develop online, open, multilingual psychometric assessment systems. The psychological instruments have been independently developed by Vivek Belhekar and collaborators outside the purview of M-OPC. Individuals who respond to the tests or scales get feedback on their test scores. Researchers at M-OPC use this data to model psychological processes and understand people better. The M-OPC can release public-policy documents on the basis of the data analysed and help public policy achieve better outcomes. The reports are generated under the T&C of M-OPC. M-OPC shall result in courses, research papers, and other research and public dissemination.

This project PI is currently based at the Department of Applied Psychology, University of Mumbai.

M-OPC has been developed with the personal funding of Dr Vivek Belhekar.

**Objectives of M-OPC:**

-   To develop online, open, multilingual psychometric assessment system that is free of use.

-   To enhance methods and knowledge of psychometric measurement in theory and practice.

-   To enable web-based, open-source programs for data collection in psychological research.

-   To make psychological tests available to people in local languages of India.

-   To enable use of indigenous measures and norms while providing personalized feedback to test-takers.

**Types of Psychological Tests:**

**Personality**: When we talk about ourselves or other people, we often refer to personality characteristics. Like, "I am a shy person" or "He is a trustworthy person". Judgments about personality are everyday activities we engage in. Understanding our personality helps us to know how we behave in situations, feel about specific incidents, react to people, make decisions, etc. Having an insight into our personality traits gives us the power to understand ourselves better and modify our behaviours and reactions more effectively. The personality tests available on M-OPC aim to provide insights into how a person thinks, feels, and interacts with the world around them.

**Cognitive Ability**: This domain helps us to understand our abilities and mental capacity to process information, think critically, solve problems, and learn new concepts. Though it is considered most useful for academic achievements, it can also predict performance at work, relationships with people, and ability to solve day-to-day problems. It contributes to a person's intellectual functioning and adaptability. Understanding cognitive abilities helps us to organize our problem-solving strategies, decision-making, and thinking in a better manner. These tests often have a correct answer that needs to be chosen in the least time possible.

**Interests**: Interests are the subjects, activities, or pursuits that attract our attention, evoke passion, and give us a sense of purpose. We are likely to be more satisfied at work if it is something we are interested in and can do efficiently. Interest assessment helps us know which activities we like and our best competencies. This is used to map occupations that are best suited for us. These can be vocational (that helps us decide our career) or avocational (like hobbies) that can guide various recreations that bring higher satisfaction. 

**Emotions**: Emotions play a central role in human experience and greatly influence our thoughts, behaviors, and interactions. Almost every situation, person, or object generates some set of emotions for us. Some we are very well aware of, others we cannot easily name. Various tests on this portal measure current emotional state or feelings towards particular objects like climate change, one's city, one's relationships, etc. Understanding our levels of Happiness, Anger, Sadness, Curiosity, etc. is likely to help us function in an emotionally healthy manner.

**Industrial and Organizational Behaviour**: Several components in organizational behaviour influence the well-being and growth of the organization and its employees. These include satisfaction with the job, attitudes towards the work environment, commitment to the organization, etc. Knowing employees' levels on such variables can help organizations in recruitment, training, interventions, HR management, etc.

If you want to help us develop our understanding of personality and culture in India, please take our test at M-OPC.

^1^It was formerly called MU-OPC. All rights (including intellectual) of the projects MU-OPC and M-OPC are with Dr. Vivek Belhekar.
